// MedLingo — 藥理學題庫 v1.0
// 動態載入後設定: window.ML_P = { id:'p', ms:[...] }
(function(){
'use strict';
const Q=(q,o,a,e)=>({q,o,a,e});
const ms=[

/* ===== M1 受器藥理學 ===== */
{id:1,title:'受器藥理學',em:'🔬',c:'#2EC4B6',
u:[
{id:'a',t:'受器分類與訊號傳遞',em:'📡',qs:[
Q('下列哪種受器直接耦合離子通道（Ionotropic）？',
['β₁腎上腺素受器（Gs耦合）','M₂毒蕈鹼受器（Gi耦合）','菸鹼型乙醯膽鹼受器（nAChR）','α₁腎上腺素受器（Gq耦合）'],2,
'Ionotropic受器=配體門控離子通道，訊號最快。nAChR（N₁/N₂）為代表。其他均為GPCR（Metabotropic）。'),
Q('Gs蛋白耦合受器活化後的下游訊號？',
['Gαs→抑制adenylyl cyclase→cAMP↓','Gαs→活化adenylyl cyclase→cAMP↑→PKA活化','Gαq→PLC→IP₃→Ca²⁺','Gαi→cAMP↑'],1,
'Gs→adenylyl cyclase↑→cAMP↑→PKA活化。β₁/β₂腎上腺素、D₁、H₂、V₂均耦合Gs。記憶：Gs=Go stimulate。'),
Q('受器去敏化（Desensitization）的主要機制？',
['G蛋白基因突變','受器磷酸化（GRK）→arrestin結合→內吞→降解','cAMP蓄積毒殺細胞','腺苷酸環化酶被分解'],1,
'GRK磷酸化活化態受器→β-arrestin結合→（1）阻斷G蛋白耦合；（2）引導受器內吞→degradation。長期使用β₂agonist效果↓的原因。'),
Q('競爭性拮抗劑的作用特點？',
['Emax降低，EC₅₀不變','EC₅₀增大（劑量反應曲線右移），Emax不變，可被高劑量促效劑克服','EC₅₀不變，Emax降低','不可逆，Emax永久降低'],1,
'競爭性拮抗劑（可逆）：EC₅₀↑但Emax不變，高濃度促效劑可克服。例：Atropine（競爭性M受器拮抗）。非競爭性（不可逆）：Emax↓，無法被克服。'),
Q('治療指數（TI）的公式及意義？',
['TI=ED₅₀/TD₅₀','TI=TD₅₀/ED₅₀，越大越安全','TI=LD₅₀/ED₁₀₀','TI=EC₅₀/LC₅₀'],1,
'TI=TD₅₀/ED₅₀。TI小→有效劑量與毒性劑量接近→需TDM。TI小的藥：Digoxin、Lithium、Warfarin、Phenytoin、Aminoglycosides。'),
]},
{id:'b',t:'藥效動力學基礎',em:'📈',qs:[
Q('「效能（Efficacy）」vs「效力（Potency）」的差異？',
['效力決定最大療效','效能=Emax（最大療效），效力=達50%最大效應所需劑量的倒數（EC₅₀）','兩者相同','效力高一定療效更好'],1,
'Efficacy（效能）=Emax=藥物質的能力。Potency（效力）：EC₅₀越低→效力越高。Morphine efficacy>Codeine；Fentanyl potency>Morphine（達同效需更小劑量）。'),
Q('長期使用β阻斷劑後突然停藥，可能引發什麼？',
['血壓急速下降','受器上調（Up-regulation）→停藥後對β受器刺激過度敏感→反彈性心搏過速/心絞痛加重','無任何影響','自律神經穩定'],1,
'受器上調=長期被拮抗→受器代償性增多/增敏。β阻斷劑不可突然停藥原因。類似機制：長期使用可樂定突然停藥→高血壓危象。'),
Q('部分促效劑（Partial agonist）在有Full agonist存在時的特殊效應？',
['加強Full agonist效果','競爭佔據受器→降低整體效應→表現為「功能性拮抗」；Buprenorphine就有此特性','無影響','完全被Full agonist取代'],1,
'部分促效劑在Full agonist存在時：競爭佔受器→Emax↓→功能性拮抗（更像拮抗劑）。Buprenorphine（部分μ促效劑）高劑量可封鎖其他阿片類。這是其用於阿片戒毒的重要機制。'),
Q('藥物耐受性（Tolerance）的兩種主要機制？',
['過敏反應','（1）藥動學耐受：酵素誘導→代謝加速→血濃度↓；（2）藥效學耐受：受器去敏化/down-regulation→敏感度↓；兩者均需增量維持效果','只與遺傳有關','所有藥物都有耐受'],1,
'耐受≠依賴≠成癮。Tolerance例：硝酸鹽（需8-12hr空窗期）、阿片類、BZD、酒精。交叉耐受（Cross-tolerance）：同類藥物間的耐受轉移（如酒精+BZD交叉耐受）。'),
Q('藥物的「一級（First-order）動力學」vs「零級（Zero-order）」的差異？',
['只有靜脈給藥才有一級動力學','一級：排除速率∝濃度→t₁/₂恆定（大多數藥物）；零級：固定速率排除→無固定t₁/₂→濃度稍增→毒性急升；零級例：Phenytoin（高濃度）、Alcohol（高濃度）','所有藥物均為零級','零級動力學更安全'],1,
'零級動力學藥物臨床危險：濃度輕微增加→毒性大幅增加。Phenytoin：治療指數窄+零級動力學→需TDM。酒精：每小時代謝約10g→固定速率。一級動力學：5個t₁/₂達穩態（Steady state）。'),
]},
{id:'c',t:'藥物動力學',em:'⚗️',qs:[
Q('分佈體積（Vd）很大的藥物（如Digoxin, Chloroquine），其臨床意義？',
['容易用血液透析清除','大量分布在組織（Vd大→血漿濃度低）→血液透析或強迫利尿效果差→過量時需特異性解毒劑；Digoxin過量→Digoxin-specific Fab（唯一有效）','容易被腎臟清除','蛋白結合率低'],1,
'Vd=Amount in body/Plasma concentration。Vd大→脂溶性高/組織結合強→血漿濃度低→洗胃/透析效果差。Vd小（如Lithium, Aspirin）→主要在血漿→透析有效。'),
Q('CYP3A4強抑制劑（如Clarithromycin）與Colchicine合用的風險？',
['無交互作用','CYP3A4抑制→Colchicine代謝↓→血濃度暴增（5-10倍）→嚴重毒性（嚴重GI/骨髓抑制/橫紋肌溶解）；腎衰竭時更危險→需減量或換抗生素','代謝加速→效果↓','只影響Clarithromycin'],1,
'Colchicine：CYP3A4+P-gp底物。強CYP3A4+P-gp抑制劑（Clarithromycin）→Colchicine暴露量大增→嚴重毒性甚至致命。替代：Azithromycin（較弱CYP抑制）。腎衰竭+Colchicine+Clarithromycin→絕對禁忌。'),
Q('P糖蛋白（P-gp）在Digoxin的臨床意義？',
['P-gp無臨床意義','P-gp（外排泵）限制Digoxin在腸道的吸收和腎臟排泄；P-gp抑制劑（Verapamil/Quinidine/Amiodarone）→Digoxin血濃度↑（可達2倍）→毒性風險↑','P-gp促進Digoxin吸收','只影響CNS藥物'],1,
'P-gp=MDR1/ABCB1：腸道（限制吸收）、BBB（限制腦穿透）、腎臟/肝臟（排泄）。重要Digoxin交互作用：Amiodarone、Verapamil、Quinidine、Clarithromycin→Digoxin濃度加倍→需減量50%。'),
Q('口服生體可用率（F）和首通效應（First-pass）的關係？',
['F只與腸道吸收有關','F=腸道吸收×（1-首通代謝）；強首通效應→口服F低（如Morphine F≈30%、Lidocaine F≈35%、NTG F<10%）→舌下/靜脈給藥可繞過首通→F=100%（IV）','靜脈給藥F<100%','肝臟無首通效應'],1,
'首通效應（Hepatic first-pass）：口服→腸道→門靜脈→肝臟→全身循環，途中大量代謝→F↓。舌下NTG（吞服無效，因強首通）。Propranolol oral F≈30%（強首通）→口服劑量需遠大於IV劑量。'),
Q('Half-life（t₁/₂）與穩態（Steady state）的關係？',
['穩態在第2個t₁/₂達到','第5個t₁/₂達穩態（約97%）；t₁/₂增加→達穩態時間延長，但穩態濃度不變（由劑量/清除率決定）；腎/肝衰竭→t₁/₂↑→達穩態更慢+可能蓄積','t₁/₂只與劑量有關','穩態後t₁/₂不再重要'],1,
'5×t₁/₂達穩態（Css）。Css由給藥速率/清除率決定（與t₁/₂無關）。Loading dose：想快速達治療濃度→給loading dose（不等穩態）。例：Digoxin（t₁/₂=36hr）→穩態需7-8天，緊急情況先給loading dose。'),
]},
boss:[
Q('一位32歲女性，花粉過敏引發急性蕁麻疹+支氣管痙攣，需Epinephrine。其主要受器機制？',
['純α₁→血管收縮','純β₂→支氣管擴張','α₁（血管收縮/減少蕁麻疹腫脹）+β₁（心臟支持）+β₂（支氣管擴張）多重協同救命效果','D₁→腎血管擴張'],2,
'過敏性休克Epinephrine機制：α₁→血管收縮（逆轉低血壓+止蕁麻疹腫脹）；β₂→支氣管擴張；β₁→↑心輸出；並穩定肥大細胞（↓組織胺釋放）。IM大腿外側（1:1000, 0.3mg）是標準路徑。'),
Q('Naloxone逆轉Buprenorphine（高親和力部分促效劑）過量，效果為何？',
['與逆轉嗎啡完全相同','Buprenorphine對μ受器親和力極高且解離慢→Naloxone競爭置換困難→需更高劑量且效果仍有限；因Buprenorphine t₁/₂長（24-60hr）→拮抗後需持續監測再麻醉','完全無效','Buprenorphine不造成呼吸抑制'],1,
'Buprenorphine親和力極高（Kd極低）+慢解離→Naloxone置換困難。策略：大量持續輸注Naloxone+呼吸支持。Buprenorphine t₁/₂=24-60hr→Naloxone（t₁/₂=30-90min）→再麻醉風險高→需長期監測。'),
Q('有機磷農藥中毒（AChE不可逆抑制）的DUMBELS症狀及治療？',
['散瞳、心搏過速、皮膚乾燥；治療β阻斷劑','縮瞳、大量流涎/流淚/排尿/腹瀉、心搏過緩/支氣管痙攣/分泌↑、肌肉抽搐；治療：（1）Atropine大量（阻斷M症狀）；（2）Pralidoxime（老化前重活化AChE）；（3）BZD（肌肉抽搐）','高血壓危象','所有症狀均需Pralidoxime'],1,
'DUMBELS=D（Diarrhea/Diaphoresis）U（Urination）M（Miosis）B（Bradycardia/Bronchospasm/Bronchosecretion）E（Emesis）L（Lacrimation）S（Salivation/Sweating）。老化（Aging）：OP-AChE複合體去烷基化→不可逆→Pralidoxime無效→需在4-6hr內給予。'),
Q('一位65歲男性使用Rifampin治療TB+Warfarin抗凝（INR 2.5）。兩週後INR降至1.2。原因？',
['Rifampin與Warfarin無交互作用','Rifampin（最強CYP450誘導劑）→CYP2C9（代謝S-Warfarin的主要酶）↑→Warfarin代謝加速→血中濃度↓→INR↓↓；需顯著增加Warfarin劑量（可能2-3倍）+每週INR監測','Warfarin代謝受腎臟影響','只是感染使INR下降'],1,
'Rifampin：誘導CYP1A2/2C9/2C19/3A4+P-gp→幾乎影響所有CYP底物。Warfarin（S型）主要CYP2C9代謝→Rifampin→代謝↑→INR↓。停Rifampin後誘導消失（需回調Warfarin劑量防出血）。其他重要Rifampin交互作用：OCP（避孕失效）、Methadone（戒斷）、Cyclosporine（排斥）。'),
Q('Digoxin治療指數小（TI=TD₅₀/ED₅₀），其監測重點有哪些？',
['只監測心率','（1）血清Digoxin濃度（目標0.5-0.9 ng/mL，舊版1-2 ng/mL增加死亡率）；（2）腎功能（腎清除為主→腎衰→蓄積）；（3）電解質（低K⁺→Na/K-ATPase競爭↓→毒性↑；低Mg²⁺→加劇）；（4）藥物交互作用（P-gp抑制劑→濃度倍增）；毒性：黃綠視、AV block、VT','只監測INR','只監測腎功能即可'],1,
'Digoxin毒性症狀：GI（噁心/嘔吐）+視覺（黃綠色視、光暈）+心律不整（AV block各程度、心室快速心律）。毒性誘因：腎衰、低鉀（最重要）、低鎂、甲狀腺功能低下。Digoxin特異性Fab片段（Digibind/DigiFab）：嚴重中毒唯一有效解毒（Vd大→透析無效）。'),
Q('Amiodarone長期使用後甲狀腺功能異常，機制為何？Amiodarone引起甲亢vs甲低的鑑別？',
['Amiodarone不影響甲狀腺','Amiodarone含碘（37%重量）→（1）甲低（Hypothyroidism）：Wolff-Chaikoff效應（大量碘→暫時抑制T4/T3合成）；（2）甲亢（Hyperthyroidism）：Type 1（碘負荷→自律甲狀腺合成↑，有既往甲狀腺異常）vs Type 2（破壞性甲狀腺炎→T4/T3釋放）；監測：TSH最敏感','只引起甲低','碘含量低，無甲狀腺影響'],1,
'Amiodarone甲亢Type 1：彩色都普勒顯示血管化↑→Thionamide（MMI/PTU）治療。Type 2：破壞性→類固醇治療（抑制炎症）。區別：難以鑑別時→合用兩種治療。Amiodarone t₁/₂長（40-55天）→停藥後甲狀腺異常仍可持續數月。TSH是最敏感的早期指標（比FT4更早異常）。'),
]},

/* ===== M2 擬交感/拮抗藥 ===== */
{id:2,title:'擬交感/拮抗藥',em:'⚡',c:'#FF6B6B',
u:[
{id:'a',t:'α受器藥物',em:'🎯',qs:[
Q('Phenylephrine（苯腎上腺素）的主要藥理作用？',
['α₁選擇性→血管收縮→BP↑+反射性HR↓','β₁促效→HR↑','非選擇性','α₂促效→中樞降壓'],0,
'Phenylephrine：選擇性α₁促效→SVR↑→BP↑→壓力感受器反射→vagal reflex→HR↓。用途：局部鼻充血、眼科散瞳、術中低血壓（純升壓不增HR，適合HR已快的患者）。無β活性。'),
Q('Clonidine（可樂定）突然停藥的危險？',
['無任何危險','反彈性高血壓（Rebound hypertension）：長期使用→α₂受器上調→突然停藥→交感輸出急增→高血壓危象。需緩慢減量。類似機制：長期β阻斷劑突然停藥→反彈性心絞痛/AMI','血壓急速下降','呼吸抑制'],1,
'Clonidine：中樞性α₂促效劑→延腦交感輸出↓→HR↓, BP↓。突然停藥→受器上調→交感↑↑→高血壓危象（可在12-48hr內發生）。治療：重新給予Clonidine+緩慢減量，或換用其他降壓藥。'),
Q('嗜鉻細胞瘤術前準備：α先還是β先？',
['先β阻斷劑，再α阻斷劑','必須先α阻斷劑（Phenoxybenzamine至少10-14天）→血壓穩定+血容量恢復→再加β阻斷劑；若先β：β₂血管擴張效應消失，只剩純α收縮→血壓危象','同時給予','不需術前準備'],1,
'先β阻斷劑的危險：β₂阻斷→骨骼肌/腸繫膜血管擴張消失→只剩α₁收縮→血壓急升。記憶：「先α後β，規矩不亂」。Phenoxybenzamine（不可逆非選擇性α阻斷）→長期穩定血壓+讓血容量恢復（Hematocrit↓=血容量充足的標誌）。'),
Q('α₁拮抗劑（Prazosin）的首劑效應（First-dose effect）？',
['血壓緩慢下降（安全）','首次給藥後30-90分鐘出現嚴重直立性低血壓→暈厥；對策：睡前低劑量服藥，服藥後保持臥位至少1小時','只在高劑量時發生','Tamsulosin也有嚴重首劑效應'],1,
'Prazosin首劑效應：非選擇性α₁阻斷→全身血管急速擴張→直立性低血壓。Tamsulosin（α₁A選擇性）：攝護腺>血管，首劑效應較少。BPH治療選擇：Tamsulosin（安全）或Prazosin（同時有降壓需求時更適合）。'),
Q('MAOi+Tyramine（乳酪反應）的機制？',
['直接過敏反應','腸道MAO-A被MAOi抑制→飲食Tyramine大量吸收→進入交感末梢觸發NE釋放（間接促效）→高血壓危象（可致腦中風）','Tyramine抑制腎素','D₁受器直接效應'],1,
'MAOi飲食限制：陳年起司/紅酒/發酵食品（高Tyramine）。治療高血壓危象：Phentolamine IV（非選擇性α阻斷）或Nitroprusside。MAO-A（腸道）：代謝5-HT、NE、Tyramine→被MAOi阻斷後Tyramine吸收↑。MAO-B（DA）：選擇性MAO-B抑制（Selegiline）→較少乳酪反應。'),
]},
{id:'b',t:'β受器藥物',em:'💓',qs:[
Q('Carvedilol vs Metoprolol的藥理差異？',
['兩者完全相同','Carvedilol：非選擇性β阻斷+α₁阻斷→血管擴張（後負荷↓）；Metoprolol：β₁選擇性阻斷（無α阻斷）；HFrEF均可用，Carvedilol後負荷↓效果對心衰竭更有利','Metoprolol更適合心衰竭','Carvedilol只用於高血壓'],0,
'Carvedilol在HFrEF：COPERNICUS試驗→EF<25%嚴重心衰竭也有效。三個α+β阻斷劑：Carvedilol、Labetalol（IV用於高血壓急症/妊娠）、Bucindolol。注意：β₂阻斷→氣喘/COPD患者謹慎。'),
Q('β阻斷劑在哪種心絞痛禁用？',
['穩定型心絞痛','Prinzmetal（血管痙攣型/Variant）心絞痛：β阻斷→α₁效應未被拮抗→冠脈痙攣加重；首選：Ca²⁺通道阻斷劑（Nifedipine/Amlodipine）+長效NTG','ACS（急性冠脈症候群）','運動誘發型心絞痛'],1,
'Prinzmetal心絞痛：夜間/休息時發作、ST段上升（暫時性）、冠脈無明顯狹窄（純痙攣）。治療：CCB（首選）+長效NTG。禁忌：β阻斷劑（α未拮抗→痙攣加重）、Aspirin（高劑量可抑制PGI₂→痙攣↑）。'),
Q('Propranolol在糖尿病患者使用的注意事項？',
['不影響血糖感知','β₁阻斷→掩蓋心悸（低血糖警告症狀被抑制）；β₂阻斷→肝糖原分解↓→延長低血糖；但膽鹼性發汗（α₁效應）仍保留→流汗是唯一剩餘警告；優先選β₁選擇性藥物（Metoprolol）以減少此問題','完全安全','β阻斷劑促進胰島素分泌→低血糖'],1,
'β阻斷劑在DM患者的風險：掩蓋低血糖+延長低血糖。β₁選擇性藥物（Metoprolol、Bisoprolol、Atenolol）→較少β₂阻斷→較少影響血糖感知。然而，HFrEF+DM患者仍應使用β阻斷劑（死亡率獲益>低血糖風險）。'),
Q('Esmolol最適合的臨床應用場景？',
['慢性高血壓長期控制','超短效β₁選擇性IV阻斷劑（t₁/₂=9分鐘，紅血球酯酶代謝）→術中心搏過速、主動脈夾層（控制HR+BP）、AF急性心率控制；可快速調整劑量','每天一次口服','運動誘發心搏過速長期預防'],1,
'Esmolol=急性快速可調節的β阻斷劑。主動脈夾層（最重要適應症）：需同時↓HR<60+SBP<120→Esmolol（HR控制）+Nicardipine（BP控制）。術後AF：Esmolol rate control，血流動力學穩定後換口服β阻斷劑。'),
Q('Dobutamine vs Dopamine在急性心衰竭/心源性休克的比較？',
['兩者相同','Dobutamine：主要β₁促效（+輕微β₂）→心臟收縮力↑+後負荷↓，對心率影響較小，心衰竭首選（CO↑, PCWP↓）；Dopamine高劑量：α₁→全身收縮→SVR↑→對心衰竭較不利（後負荷↑）；但Dopamine可用於低血壓更嚴重時（升壓效果更強）','Dopamine優先','兩者均不用於心衰竭'],0,
'心源性休克藥物選擇：（1）主要心肌抑制（EF低）→Dobutamine（正性肌力）；（2）主要血管擴張（感染性休克型）→Norepinephrine；（3）兩者兼有→可合用。Dobutamine禁/慎用：HOCM（梗阻加重）、AF（加速AV傳導）。Dobutamine stress echo（DSE）：冠心病檢查，用心臟壓力測試。'),
]},
{id:'c',t:'擬交感胺類應用',em:'🚀',qs:[
Q('Epinephrine在過敏性休克：IM vs IV的選擇？',
['IV永遠優先（更快）','急救：IM（大腿外側，1:1000, 0.3mg）→吸收快+安全（IV純Epi→心律不整危險）；IV（1:10,000）只用於心搏停止或嚴重難治型過敏性休克（需稀釋+緩慢給）','SC（皮下）最佳','兩者完全相同'],1,
'過敏性休克第一線：IM Epinephrine（大腿外側股外側肌）→Peak血中濃度在8分鐘（IM大腿）優於SC（上臂）。自動注射器（EpiPen）：0.3mg IM大腿。未給Epi直接給抗組織胺→最常見錯誤（抗組織胺不能逆轉低血壓/氣管水腫）。'),
Q('Cocaine引起心肌梗塞，為何禁用β阻斷劑？',
['β阻斷劑會加速Cocaine代謝','β阻斷→β₂血管擴張效應消失→只剩未拮抗的α₁收縮→冠脈痙攣加重+血壓↑↑（paradoxical hypertension）；治療：BZD（降交感張力）+NTG（冠脈擴張）+Ca²⁺通道阻斷劑','β阻斷劑加重心律不整','β阻斷劑與Cocaine無交互作用'],1,
'Cocaine心臟毒性：NET抑制→NE↑→冠脈痙攣（α₁）+血栓形成（血小板活化）。治療原則：BZD（降交感）+硝酸鹽（冠脈擴張）；禁：β阻斷劑（純α效應加重冠脈痙攣）。Labetalol（α+β）：有些指引認為可謹慎使用（α阻斷拮抗純α效應），但仍有爭議。'),
Q('Amphetamine vs Cocaine的機制差異？',
['兩者完全相同','Cocaine：只阻斷NET/DAT再攝取（被動機制）；Amphetamine：（1）主動進入神經末梢；（2）觸發NE/DA逆向釋放（transporter reversal）+（3）再攝取抑制+（4）弱MAO抑制→效果更強更持久','Amphetamine只作用α受器','Cocaine更危險'],1,
'Amphetamine釋放機制（Efflux）：是Cocaine（阻斷再攝取）的不同機制。兩者均↑突觸NE+DA。Methamphetamine（冰毒）：脂溶性更高→更快進入腦→更強CNS效應。臨床用途（治療）：ADHD（Adderall=Amphetamine鹽混合物）、嗜睡症（Narcolepsy）。'),
Q('Ritodrine（β₂促效劑）用於抑制早產，母體副作用為何？',
['無副作用','心悸/心搏過速（β₁cross-over）、低血鉀（K⁺進入細胞）、高血糖（肝糖原分解）、肺水腫（嚴重時）；β₂受器在子宮平滑肌→鬆弛→抑制宮縮（Tocolysis）','只有子宮鬆弛，無全身副作用','引起胎兒心搏過緩'],1,
'Ritodrine/Terbutaline（β₂促效）的Tocolytic（抑制宮縮）機制：子宮平滑肌β₂受器→cAMP↑→PKA活化→MLC去磷酸化→鬆弛。副作用主要因β₁cross-over（心臟）和β₂肝臟/骨骼肌效應。現多用Nifedipine（Ca²⁺通道阻斷劑）或Atosiban（OT拮抗劑）替代。'),
Q('Phentolamine（非選擇性α阻斷劑）的主要緊急適應症？',
['用於感染性休克升壓','嗜鉻細胞瘤高血壓危象（catecholamine過度分泌）的快速靜脈控制；也用於局麻藥含Epi注射後意外引起手指/趾缺血的拮抗（皮下注射）','急性青光眼','抗膽鹼中毒'],0,
'Phentolamine：非選擇性（α₁+α₂）競爭性可逆α拮抗劑。嗜鉻細胞瘤危象：IV Phentolamine（快速起效）→控制血壓→穩定後換口服Phenoxybenzamine。局麻含Epi意外缺血：局部皮下注射Phentolamine→逆轉α₁收縮→恢復血流。'),
]},
boss:[
Q('25歲男性急性過敏性休克（BP 70/40），立即給Epinephrine IM 0.3mg。5分鐘後症狀僅部分改善。下一步？',
['等待30分鐘再評估','可重複IM Epinephrine（0.3mg，每5-15分鐘）；同時：建立靜脈通路→大量生理鹽水補液（過敏性休克常有低容積）；若難治型→Epi IV drip或多巴胺；輔助：Diphenhydramine（抗組織胺）+類固醇（Methylprednisolone）→預防雙相反應（biphasic reaction, 4-8hr後可能復發）','改用Atropine','只給抗組織胺'],1,
'過敏性休克管理：Epi IM是核心，可重複（無禁忌）。雙相反應（Biphasic anaphylaxis）：初次緩解後4-8hr復發→至少觀察4-8hr（嚴重→24hr）。補液：過敏性休克血管擴張→大量靜脈補液（NS 1-2L fast）。Glucagon：服用β阻斷劑的患者Epi效果差→Glucagon（繞過β受器→↑cAMP）。'),
Q('70歲HFrEF患者計畫加入Carvedilol。正確的起始和滴定策略？',
['急性失代償期立即開始，大劑量','只在穩定期（無端坐呼吸/水腫/IV利尿劑需求）開始；起始：3.125mg BID→每2週倍增→目標25mg BID（或最大耐受劑量）；若急性失代償已在用β阻斷劑：維持或減量（非停藥）','心衰竭禁用所有β阻斷劑','一次給予目標劑量'],1,
'β阻斷劑HFrEF的「黃金」：在穩定基礎上開始，慢慢titrate。急性失代償→停用β阻斷劑（心肌抑制加重）。穩定後重新開始。MERIT-HF（Metoprolol CR/XL）+CIBIS-II（Bisoprolol）+COPERNICUS（Carvedilol）→三大里程碑試驗→死亡率↓25-35%。'),
Q('嗜鉻細胞瘤術中：切除腫瘤後患者突發嚴重低血壓（BP 60/30）。機制及處置？',
['術中血壓突降=血管迷走性暈厥','Catecholamine急速↓（腫瘤切除後分泌消失）+術前α阻斷劑血管擴張→嚴重低血壓；處置：大量靜脈補液（術前α阻斷治療已讓血容量恢復）+Norepinephrine IV（升壓）+Dopamine（支持心臟）；術前充分補液是關鍵預防措施','給Epinephrine大劑量','只補液，不需升壓藥'],1,
'嗜鉻細胞瘤術中血流動力學曲線：（1）術中操作腫瘤→catecholamine急升→血壓危象→Phentolamine/Labetalol IV；（2）切除腫瘤後→catecholamine急降→嚴重低血壓→補液+升壓藥。麻醉醫師必須預備兩套相反的藥物！術前充分α阻斷+補液是降低術後低血壓的關鍵。'),
Q('45歲女性，Grave\'s病（甲亢），心率120次/分，顫抖明顯。等待Methimazole起效期間，可加用哪種藥物緩解症狀？',
['立即給予放射碘治療','Propranolol（非選擇性β阻斷劑）：（1）β₁阻斷→HR↓（緩解心悸/顫動）；（2）額外效應：抑制外周T4→T3轉化（5\'脫碘酶抑制）→FT3↓；（3）甲狀腺危象時需大劑量（60-80mg q4h）；只是症狀控制，不影響甲狀腺素合成','Atropine','給Thyroxine（T4）'],1,
'甲亢β阻斷劑用途：（1）橋接治療（等待抗甲狀腺藥起效期間）；（2）甲狀腺危象的緊急心率控制；（3）術前控制（甲狀腺手術前配合Lugol\'s碘）。Propranolol抑制T4→T3轉化（額外作用）。PTU也抑制T4→T3轉化（雙重機制，甲狀腺危象優選PTU）。'),
Q('一位服用非選擇性β阻斷劑（Nadolol）的患者需要緊急麻醉，術中出現支氣管痙攣。處置？',
['給更多β阻斷劑','支氣管痙攣（β₂阻斷→支氣管收縮）：（1）吸入β₂促效劑（Albuterol/Salbutamol）：競爭β₂受器（需高濃度克服拮抗）；（2）IV Magnesium sulfate（直接支氣管擴張）；（3）抗膽鹼吸入劑（Ipratropium）；（4）IV Aminophylline（茶鹼類，PDE抑制→cAMP↑）；注意：Epinephrine可用但β₂效應部分被阻斷','只需提高吸入氧濃度','停止麻醉'],1,
'β阻斷劑引起支氣管痙攣的機制：β₂阻斷→支氣管平滑肌cAMP↓→收縮。高劑量吸入β₂agonist可克服（競爭性）。Ipratropium（M受器阻斷）：不依賴β受器→有效。IV Mg²⁺：直接支氣管擴張機制（阻斷Ca²⁺）。IV Aminophylline：PDE抑制→cAMP↑→支氣管擴張（作用不依賴β受器）。'),
]},

/* ===== M3 膽鹼藥物 ===== */
{id:3,title:'膽鹼藥物',em:'🧪',c:'#7C69EF',
u:[
{id:'a',t:'擬膽鹼藥',em:'🐢',qs:[
Q('Physostigmine vs Neostigmine穿越BBB的差異及臨床意義？',
['兩者均穿越BBB','Physostigmine（叔胺）穿越BBB→可逆轉CNS抗膽鹼毒性（混亂/幻覺）；Neostigmine（季銨基）不穿越BBB→只逆轉NMJ肌鬆+周邊M效應，不影響CNS；抗膽鹼中毒（TCA/抗組織胺過量）：Physostigmine可治療CNS症狀（但TCA+Physostigmine→心臟毒性，禁忌！）','Neostigmine穿越BBB','兩者均不穿越BBB'],1,
'叔胺（Tertiary amine）=不帶電荷=穿越BBB（Physostigmine、Scopolamine、Atropine）。季銨（Quaternary ammonium）=帶電荷=不穿越BBB（Neostigmine、Glycopyrrolate、Ipratropium）。臨床意義：CNS抗膽鹼中毒→Physostigmine；NMJ逆轉→Neostigmine（不影響腦）。'),
Q('有機磷「老化（Aging）」現象的臨床意義？',
['AChE自然恢復的過程','OP-AChE複合體去烷基化→不可逆結合（即使Pralidoxime也無法重活化）；時間約4-6小時（Soman老化更快~2分鐘）；老化後→只能Atropine（症狀控制），無法逆轉AChE','Pralidoxime的治療窗口','膽鹼能受器的去敏化'],1,
'老化前給Pralidoxime（2-PAM）=關鍵時間窗口。Pralidoxime作用：與OP-AChE複合體中的OP結合→將OP從AChE上拉開（反應更強的親核劑）→AChE重活化→恢復ACh水解能力。Soman（GB）老化極快（2-5分鐘）→Pralidoxime幾乎無效→神經毒劑預防：Pyridostigmine（預防性AChEI讓活性位被佔→OP無法結合）。'),
Q('Bethanechol用於術後尿瀦留的機制及禁忌？',
['阻斷膀胱M受器','刺激膀胱逼尿肌M₃受器→逼尿肌收縮→排尿；禁忌：尿道梗阻（前列腺腫大嚴重）、消化道梗阻（腸道穿孔風險）、哮喘（M₃→支氣管收縮）；不被AChE水解（比ACh更持久）','阻斷膀胱α受器','直接鬆弛尿道括約肌'],1,
'Bethanechol vs Pilocarpine：Bethanechol→主要膀胱/腸道（周邊M選擇性，不穿BBB）；Pilocarpine→主要眼科/口腔（唾液腺）。Carbachol（膽鹼類）：同時作用M+N受器，眼科用（縮瞳）。術後腸麻痺：Metoclopramide（D₂拮抗，促進腸蠕動）也常用。'),
Q('重症肌無力（MG）的病理機制及Pyridostigmine的作用？',
['NE受器抗體','IgG抗體攻擊NMJ突觸後nAChR（N₁受器）→受器數量/功能↓→神經肌肉傳遞↓→肌肉無力（眼肌最先，午後加重）；Pyridostigmine（可逆AChEI，季銨，不穿BBB）→ACh蓄積→彌補減少的nAChR→肌力改善；長期治療：免疫抑制（類固醇/Azathioprine/MMF）','突觸前ACh合成不足','突觸後M受器問題'],1,
'MG Pyridostigmine vs Neostigmine：Pyridostigmine較長效（口服，每4-6hr）→MG長期治療首選。Neostigmine：較短效，急性診斷/術後使用。Edrophonium（Tensilon）：極短效（5-10分鐘）→診斷MG（Tensilon test）。過量AChEI→膽鹼能危象（Cholinergic crisis）→DUMBELS→停藥+Atropine。'),
Q('Succinylcholine的高血鉀副作用：誰是高危族群？',
['所有患者均有嚴重風險','嚴重燒傷（72hr後至癒合前）、脊髓損傷/截癱（1週後至6個月）、長期固定不動、橫紋肌溶解症→這些情況→肌肉upregulate extrajunctional nAChR→去極化面積↑→大量K⁺流出→高血鉀→室顫','只有腎衰竭患者','任何患者均有'},0,
'正常K⁺升高：0.5 mEq/L（無害）。高危情況：extrajunctional nAChR（α₇同聚體）上調→Succinylcholine→大量K⁺流出→K⁺升高2-8 mEq/L→致命高鉀。高危患者→改用Rocuronium（非去極化肌鬆劑）+Sugammadex。Malignant Hyperthermia（MH）：Succinylcholine+揮發性麻醉藥→RYR1突變→Ca²⁺大量釋放→高代謝狀態→Dantrolene治療。'),
]},
{id:'b',t:'抗膽鹼藥',em:'🚫',qs:[
Q('Atropine過量的中毒症狀（抗膽鹼毒素症候群）？',
['DUMBELS（膽鹼能亢進症狀）','「Blind as a bat（散瞳）、Burning hot as a hare（高體溫）、Dry as a bone（口乾/皮膚乾）、Mad as a hatter（CNS混亂）、Full as a flask（尿瀦留）」→皮膚乾紅熱、心搏過速、腸蠕動↓','縮瞳、腹瀉、心搏過緩','肌肉強直、高熱'],1,
'抗膽鹼毒素症候群 vs 膽鹼能毒素症候群（DUMBELS）：完全相反。關鍵鑑別：縮瞳（膽鹼能）vs 散瞳（抗膽鹼）。抗膽鹼中毒治療：Physostigmine（叔胺AChEI，穿BBB）→逆轉CNS和周邊M症狀。禁忌：TCA（三環抗憂鬱）引起的抗膽鹼中毒→Physostigmine加重心臟毒性。'),
Q('Ipratropium（LAMA類）vs 全身性Atropine的差異？',
['兩者相同，都有全身副作用','Ipratropium：季銨鹽→吸入後不被全身吸收/不穿BBB→局部支氣管M₃拮抗→支氣管擴張；心臟/CNS副作用最小；Tiotropium（長效版，每天一次）；Atropine：叔胺→全身吸收→多種受器副作用（心率↑/口乾/尿瀦留）','Ipratropium有更多全身副作用','季銨鹽穿越BBB'],0,
'吸入性抗膽鹼劑（LAMA = Long-acting Muscarinic Antagonist）：COPD治療核心。LAMA vs LABA（長效β₂促效劑）組合→最強效COPD控制。Tiotropium（Spiriva）：每天一次LAMA→COPD首選長期藥物（UPLIFT試驗）。在哮喘：LAMA作為附加治療（GINA指引）。'),
Q('Atropine治療心搏過緩時，低劑量可能引起矛盾效應？',
['低劑量更安全','低劑量Atropine先阻斷突觸前M₁自體受器（負回饋受器）→ACh釋放↑→心率短暫↓（矛盾效應）；需給足夠劑量（0.5mg IV，最大3mg）才能有效阻斷突觸後M₂→HR↑','Atropine低劑量升HR更多','低劑量只影響周邊'],1,
'臨床意義：急性心搏過緩（AMI/迷走神經張力過高）→Atropine需從0.5mg IV開始（不要從0.1-0.2mg開始，可能引起矛盾性HR↓）→最大3mg（完全拮抗量）。Atropine無效的心搏過緩（如完全心搏停止）→Pacing（外部心臟起搏）。'),
Q('Scopolamine（東莨菪鹼）的特殊用途及老年人注意事項？',
['只用於胃潰瘍','抗暈動症（Motion sickness）：叔胺→穿BBB→抑制前庭核M受器；耳後貼片（Scopolamine patch, 72hr）；術前鎮靜+遺忘；老年人注意：CNS抗膽鹼副作用（意識混亂/幻覺）→使用需謹慎，考慮改非藥物方法','治療帕金森氏症','治療心搏過緩'],1,
'抗暈動症預防：最有效藥物→Scopolamine耳後貼片（出發前4hr貼上）。老年人CNS抗膽鹼效應：意識混亂、幻覺、跌倒（「Beer\'s criteria高風險藥物」）。其他抗暈動症：Dimenhydrinate/Diphenhydramine（H₁抗組織胺，有抗膽鹼副作用）、Promethazine（+CNS抑制）。Meclizine：前庭H₁拮抗，副作用較少。'),
Q('Atropine在急性閉角型青光眼中是禁忌的原因？',
['散瞳縮小房角→眼壓↑','Atropine阻斷M₃（瞳孔括約肌/睫狀肌）→散瞳→虹膜周邊堵住前房角→房水引流↓→眼壓急升（從正常25升至40-70 mmHg）→急性視力喪失；青光眼患者禁用所有散瞳藥（包括抗組織胺/抗精神病藥/TCA的抗膽鹼副作用也可誘發）','縮瞳引起眼壓↑','只在高劑量才有影響'],0,
'急閉角型青光眼誘因：散瞳（黑暗、散瞳眼藥、全身抗膽鹼藥）→虹膜根部阻塞→房水無法從後房流入前房→眼壓急升。治療：Pilocarpine（縮瞳）+Acetazolamide+β阻斷劑眼藥+Mannitol→雷射Iridotomy（根本）。Timolol眼藥水（β阻斷）：降眼壓，但也可能被全身吸收→氣喘/心搏過緩。'),
]},
{id:'c',t:'神經肌肉藥物',em:'💪',qs:[
Q('Botulinum toxin A（肉毒桿菌毒素）的臨床用途？',
['只用於美容','（1）美容（臉部皺紋，最廣泛）；（2）偏頭痛預防（每3月注射）；（3）頸肌張力不全/眼瞼痙攣/斜視；（4）多汗症（局部注射）；（5）膀胱過動症（逼尿肌注射）；（6）痙攣（腦中風/腦性麻痺後）；（7）食道失弛緩症（括約肌注射）','只用於肉毒桿菌中毒治療','只用於眼科'],1,
'BoTox作用：裂解SNARE蛋白（SNAP-25等）→ACh囊泡不能融合→ACh不能釋放→弛緩性麻痺。作用持續3-4個月（神經末梢再生後恢復）。肉毒桿菌中毒（食物型）：毒素被吸收→下行麻痺（先眼部/吞嚥困難→呼吸肌）→支持治療+抗毒素（只在早期有效）。'),
Q('LEMS（Lambert-Eaton）vs MG的電生理差異？',
['兩者EMG完全相同','LEMS：突觸前VGCC抗體→低頻重複刺激→decrement（振幅↓）；高頻重複刺激（50Hz）→increment（振幅↑，因Ca²⁺蓄積→ACh釋放↑）；MG：突觸後nAChR抗體→低頻重複刺激→decrement；高頻→無明顯increment','MG高頻刺激振幅增加','LEMS EMG正常'],1,
'LEMS診斷：（1）EMG：高頻刺激→Increment（特異性）；（2）VGCC抗體（P/Q型）；（3）肿瘤篩查（SCLC, 小細胞肺癌, 50-60%）。治療：3,4-DAP（3,4-Diaminopyridine）阻斷K⁺通道→神經末梢去極化延長→Ca²⁺流入↑→ACh釋放↑。Pyridostigmine可輔助。'),
Q('Sugammadex的作用機制及優勢？',
['核糖體阻斷','γ-cyclodextrin→特異性包裹Rocuronium/Vecuronium分子形成複合物→從nAChR解離→肌肉活動恢復；優勢：（1）可逆轉任何深度阻斷（NMT=0也可），Neostigmine做不到；（2）無需Atropine/Glycopyrrolate合用；（3）更快速完全逆轉；（4）緊急氣道（無法插管無法通氣）→Sugammadex立即逆轉Rocuronium','直接阻斷ACh','Ca²⁺通道'],0,
'Sugammadex（Bridion）：高選擇性→只對Rocuronium/Vecuronium（不逆轉Succinylcholine、Atracurium、Mivacurium）。深度阻斷逆轉：現代RSI新選擇—Rocuronium 1.2mg/kg（等效Succinylcholine起效）+Sugammadex逆轉（vs Succinylcholine無法逆轉）。禁忌：Progesterone（包含在某些避孕藥）→Sugammadex可能降低避孕效果（Rocuronium包裹→競爭）→建議使用額外避孕措施7天。'),
Q('Neostigmine逆轉肌鬆必須加抗膽鹼劑的原因？',
['Neostigmine單用即可','Neostigmine→ACh↑→NMJ（N受器）+全身M受器均刺激→腸蠕動↑、支氣管收縮、分泌↑、心搏過緩→必須加抗膽鹼劑（Glycopyrrolate或Atropine）抵消M副作用；選擇Glycopyrrolate（季銨）而非Atropine（叔胺）：不穿BBB→無術後混亂','加抗膽鹼劑反而有害','只需加Atropine'],1,
'Neostigmine+Glycopyrrolate（術後逆轉）：Glycopyrrolate優點—（1）季銨→不穿BBB；（2）起效時間與Neostigmine更匹配（vs Atropine起效更快→先心搏過速再腸蠕動↑）；（3）術後無CNS混亂（尤其老年人）。現代替代：Sugammadex（直接包裹Rocuronium）→完全省去Neostigmine+Glycopyrrolate組合。'),
Q('Myasthenia gravis危象（Myasthenic crisis）的緊急處置？',
['增加Pyridostigmine劑量','（1）氣道管理優先（插管+機械通氣）；（2）IVIG（2g/kg/5天）或血漿置換（PE，3-5次）→快速起效；（3）找誘因：感染（最常見）、手術、藥物（Aminoglycoside、Fluoroquinolone加重NMJ傳遞↓）；（4）暫時停或減Pyridostigmine（危象期過量AChEI可加重分泌/腺體症狀）；（5）穩定後重啟免疫治療','Atropine治療','只補液'],1,
'肌無力危象診斷：（1）肌無力危象（疾病加重）vs 膽鹼能危象（AChEI過量）—Edrophonium test（ICU備急救）；（2）兩者均呼吸衰竭但膽鹼能危象有DUMBELS（腸蠕動、分泌↑）。危象誘因藥物：Aminoglycosides（阻斷ACh釋放+Ca²⁺通道）、Fluoroquinolones、Mg²⁺（大量抑制ACh釋放）、Succinylcholine（去極化肌鬆→敏感性↑）。'),
]},
boss:[
Q('18歲男性，農田有機磷中毒（大量分泌+縮瞳+心搏過緩+肌肉抽搐）。Atropine的用藥目標是什麼？',
['1次2mg即可','大量給予Atropine（2mg IV每5-15分鐘重複）直到「口乾」+「支氣管分泌↓」+「支氣管痙攣緩解」——這是「阿托品化」的目標；不以「瞳孔散大」或「心率120」作為終點（這些對OP中毒不可靠）；同時給Pralidoxime（老化前）+BZD（抽搐）','只需給藥一次，等待自然恢復','Pralidoxime優先，Atropine次要'],1,
'Atropine劑量：OP中毒需求量遠超正常。嚴重中毒→可能需要數百mg Atropine。「阿托品化」終點：口乾（最客觀）+分泌↓+支氣管痙攣緩解。避免：散瞳（中毒本身縮瞳，擴大≠不適當）、心率>100（不可靠）。Pralidoxime+Atropine聯合→比單一更有效（復活AChE+阻斷M症狀）。'),
Q('65歲男性接受Rocuronium全身麻醉，手術完成需要緊急逆轉（突發性嚴重過敏反應需要插管更換路線）。最佳選擇？',
['等待Rocuronium自然代謝（45-60分鐘）','Sugammadex 16mg/kg IV（緊急逆轉劑量）→可在3分鐘內完全逆轉即使是深度阻斷（NMT=0）→允許自主通氣恢復；比Neostigmine更快/更完全（Neostigmine無法逆轉深度阻斷）','Neostigmine 0.07mg/kg（標準劑量）','給Atropine'],1,
'Sugammadex緊急逆轉劑量：16mg/kg（vs 標準逆轉2-4mg/kg）→3分鐘內完全恢復。CAN\'T INTUBATE CAN\'T OXYGENATE（CICO）情境→高劑量Rocuronium誘導插管→失敗→16mg/kg Sugammadex立即逆轉→恢復自主通氣→搶救。這是現代急救麻醉的革命性改變（以前Succinylcholine不能逆轉，Rocuronium+Sugammadex提供「保底」方案）。'),
Q('50歲男性，術後給予Neostigmine+Glycopyrrolate逆轉Vecuronium，5分鐘後出現嚴重腹痛+腸鳴音亢進+腹瀉（腸道M₃過度刺激）。Glycopyrrolate劑量不足。如何立即處理？',
['增加Neostigmine','給予額外Glycopyrrolate 0.2-0.4mg IV（補足M受器拮抗）→腸道M₃症狀↓；確認未發生過敏反應（排除腸道缺血等）；若症狀嚴重且Neostigmine已過量→Atropine（快速起效）可作補救','停Neostigmine（為時已晚）','觀察，等待自然緩解'],1,
'Neostigmine-Glycopyrrolate比例建議：Glycopyrrolate 0.2mg per Neostigmine 1mg（1:5比例）。Glycopyrrolate劑量不足→M副作用明顯（腸蠕動↑、心搏過緩）。現代趨勢：避免Neostigmine→選Sugammadex（Rocuronium/Vecuronium）→省去Glycopyrrolate合用的複雜性和副作用。'),
Q('55歲SLE患者，大量使用Dexamethasone+Cyclophosphamide治療，出現急性尿路感染（E. coli菌血症）。免疫抑制患者感染管理的特殊考量？',
['只需一般抗菌治療','（1）免疫抑制→感染可能呈現非典型表現（無高燒/白血球正常/無明顯局部症狀）→需高度警覺；（2）積極培養（血培養×2+尿培養）→抗菌治療前；（3）經驗性廣效抗菌（覆蓋G-菌，如Ceftriaxone）→依培養結果降階；（4）評估：可否暫時減少免疫抑制劑劑量（感染控制優先）；（5）監測：真菌/PCP/CMV（機會感染）','立即停所有免疫抑制','只用口服抗菌藥'],1,
'免疫抑制患者感染特點：（1）發燒可能被類固醇掩蓋（Dexamethasone退燒效應）；（2）WBC可能被Cyclophosphamide抑制（即使嚴重感染WBC也可能正常/低）；（3）更容易擴散（菌血症/敗血症）；（4）多種機會感染同時可能（PCP、CMV、Candida）。ANC<500→嚴重感染性中性球減少→住院+廣效IV抗菌+G-CSF（Filgrastim）考慮。'),
Q('30歲MG患者（穩定使用Pyridostigmine），即將行腹腔鏡膽囊切除術。麻醉醫師的特殊考量？',
['與正常患者相同','（1）避免誘發危象：感染控制、術前類固醇壓力劑量（若使用）；（2）肌鬆劑：MG患者對非去極化肌鬆劑極度敏感（nAChR數量↓）→大幅減量或完全避免；對Succinylcholine相對抵抗（受器數量↓→需增量，但高血鉀風險）；（3）Sugammadex：若用Rocuronium→逆轉更可靠；（4）術後：密切監測呼吸功能（FVC、NIV準備）','對肌鬆劑完全不敏感','只需增加Pyridostigmine劑量'],1,
'MG與麻醉：（1）非去極化肌鬆劑（Rocuronium等）：敏感度↑（需減量70-80%）→監測NMT（Train-of-Four）；（2）Succinylcholine：需增量（受器數量少）；但突然去極化→可能引起肌肉Fasciculation複雜→通常避免；（3）術後呼吸監測：MG患者術後呼吸衰竭風險（FVC<1L→高危）；（4）繼續口服Pyridostigmine（術前到最後一刻，術後儘早恢復）。'),
]},
→SGLT2i→阻斷Na⁺過度再吸收→TGF恢復→入球小動脈收縮→GFR↓（降低高濾過）→長期腎保護。'),
Q('DPP-4抑制劑（Sitagliptin）的機制及低血糖風險？',
['促進胰島素持續分泌（有低血糖）','抑制DPP-4（分解GLP-1的酶）→內源性GLP-1↑→葡萄糖依賴性促胰島素分泌+抑制升糖素；優點：不低血糖（葡萄糖依賴性，血糖正常時不刺激胰島素）、體重中立、腎功能不全可用（需減量，除Linagliptin）；效力溫和（HbA1c↓0.5-0.8%）','只用於第1型DM','效力比Metformin強'],1,
'DPP-4i vs GLP-1 RA：兩者均作用GLP-1系統，但GLP-1 RA（注射，藥理劑量）>DPP-4i（口服，生理劑量）→HbA1c降幅更大（GLP-1RA↓1-2%）+體重↓（GLP-1RA）+心血管保護（GLP-1RA）。DPP-4i優點：口服、耐受性好、無注射不便、腎功能不全可用（Linagliptin無需調整）。'),
Q('胰島素注射技術的關鍵注意事項？',
['只需確認劑量即可','（1）注射部位輪換（避免脂肪萎縮/增生）；（2）胰島素保存：未開封→冷藏（2-8°C）；已開封→室溫（<30°C）28-30天；（3）Regular insulin（短效）是唯一可IV給藥的胰島素；（4）Glargine pH=4→不可與其他胰島素混合（沉澱）；（5）速效胰島素（Lispro/Aspart）餐前5-15分鐘；Regular餐前30分鐘','所有胰島素均可IV給藥','胰島素可在任何條件下保存'],1,
'胰島素吸收差異（影響血糖控制）：腹部>上臂>大腿>臀部（吸收速度）。脂肪增生（Lipohypertrophy）：同一部位反覆注射→皮下脂肪增生→胰島素吸收不穩定→血糖控制差→「隱性問題」。胰島素泵（CSII）+CGM（持續血糖監測）=閉環系統（Artificial pancreas）→現代糖尿病管理最先進。'),
Q('Sulfonylurea（Glibenclamide/Glyburide）在老年人的危險？',
['老年人可安全使用長效SU','Glibenclamide（長效SU，t₁/₂=16hr）→持久性嚴重低血糖（SU不依賴血糖→胰島素持續分泌→即使不進食也持續）→老年人：進食不規律+腎功能↓（活性代謝物蓄積）→嚴重頑固性低血糖（反覆補葡萄糖可能需數小時-數天持續輸注）→台灣老年人禁用；改用短效SU（Glipizide, Gliclazide）或非SU降糖藥','長效SU在老年人更方便','老年人只需Metformin'],1,
'老年DM用藥原則（Beer\'s Criteria）：避免長效SU（Glibenclamide/Glyburide）→嚴重低血糖高危。優先選：（1）不低血糖藥物（DPP-4i/SGLT2i/GLP-1RA）；（2）若需SU→短效型（Glipizide）+低劑量。血糖目標：老年人適度放寬（HbA1c<8%，避免嚴重低血糖，因低血糖→跌倒→骨折→生活品質↓）。'),
]},
{id:'b',t:'甲狀腺與腎上腺藥物',em:'🌡️',qs:[
Q('甲狀腺危象（Thyroid storm）的急救藥物治療順序？',
['只需冰毯降溫','（1）PTU 600mg負荷→200mg q4h（抑制合成+T4→T3轉化）；（2）Lugol\'s碘（在PTU後1小時給，防碘被用作合成）→抑制釋放（Wolff-Chaikoff）；（3）β阻斷劑（Propranolol，控制心率+抑制T4→T3轉化）；（4）類固醇（Dexamethasone, 抑制T4→T3轉化+保護腎上腺）；（5）退燒（Acetaminophen，非Aspirin—Aspirin→FFA↑→T4游離↑→症狀加重）','只需Methimazole','立即放射碘治療'],1,
'甲狀腺危象（Burch-Wartofsky Scale>45分診斷）：死亡率10-25%。ICUCI管理：多系統支持（心跳/體溫/電解質）。治療記憶：「Block and Replace」→先阻斷合成（PTU）→再阻斷釋放（碘）→再阻斷效應（β阻斷劑）→再保護（類固醇）。碘必須在PTU「之後」給（防止碘被用作底物合成更多甲狀腺素）。'),
Q('Prednisone長期使用的骨質疏鬆預防策略？',
['只需補鈣即可','（1）基礎：Ca 1000-1500mg/day+維生素D 800-1200 IU/day；（2）使用Prednisone>7.5mg/day超過3個月→加Bisphosphonate（Alendronate/Zoledronic acid）—GRADE A推薦；（3）基礎骨密度（DXA）→追蹤；（4）最低有效劑量使用類固醇；（5）避免吸菸/酒精；機制：類固醇→破骨↑+成骨↓+腸Ca²⁺吸收↓+腎Ca²⁺排除↑→快速骨質流失','只需Bisphosphonate','只需減低類固醇劑量'],1,
'類固醇誘發骨質疏鬆（GIOP）：最常見的繼發性骨質疏鬆。骨質流失在開始使用後3-6月最快（6-12月內可失去10-20%骨密度）→早期預防（第一天就補鈣+VitD）。Bisphosphonate（Alendronate/Risedronate）：口服（需空腹+站立30分鐘→防食道刺激）或靜脈（Zoledronic acid每年1次）。Denosumab（RANK-L抑制劑）：替代（腎功能不全，Bisphosphonate禁忌時）。'),
Q('腎上腺危象（Adrenal crisis）的識別和緊急治療？',
['只需補液','臨床表現：低血壓/休克、低血糖、低鈉、高鉀（原發性腎上腺功能不全）、發燒、意識混亂；誘因：感染/手術/創傷+慢性類固醇或腎上腺功能不全患者突然停藥；緊急治療：Hydrocortisone 100mg IV stat（不要等候診斷確認）→100mg IV q8h×24hr→逐步減量；同時大量NS補液+葡萄糖（低血糖）；繼發性（垂體源）：Fludrocortisone通常不需（皮質醇降→醛固酮通常正常）','只需Fludrocortisone','等確認診斷後再治療'],1,
'腎上腺功能不全三大機制：（1）原發性（Addison病）：腎上腺皮質破壞（自體免疫最常見）→皮質醇+醛固酮均缺→低Na、高K、色素沉著、低血壓；（2）繼發性（垂體）：ACTH↓→皮質醇↓，但醛固酮正常（由腎素-血管張力素控制）；（3）三發性（下視丘）或醫源性（長期外源類固醇→HPA軸抑制）。危象診斷：AM cortisol<3μg/dL或ACTH刺激試驗陰性。'),
Q('Methimazole（MMI）vs PTU在妊娠期的選擇？',
['兩者在妊娠期完全相同','第一孕期：PTU（MMI在第一孕期→Aplasia cutis/食道閉鎖等特定致畸）；第二三孕期：換回MMI（PTU肝毒性嚴重，不適合長期；MMI第2-3孕期致畸已顯著降低）；哺乳：兩者均可（MMI首選：更方便+較少進入乳汁）；甲狀腺危象：PTU（額外抑制T4→T3轉化）','MMI在妊娠全程優先','PTU在妊娠全程優先'],1,
'甲亢妊娠管理：目標FT4在正常上限（輕度甲亢比過度治療甲低更安全）；胎兒甲狀腺在12-14週發育→MMI/PTU可透過胎盤→可能胎兒甲低→最低有效劑量；產後：甲亢通常改善（免疫耐受）→可能需減量→但產後6個月：自體免疫反彈→甲亢可能復發。放射碘（¹³¹I）：妊娠/哺乳期間絕對禁忌。'),
Q('類固醇的「應激劑量（Stress dose）」概念？',
['任何手術都需要大量類固醇','長期類固醇（>20mg prednisone equiv./>3週）→HPA軸抑制→在應激（手術/感染/外傷）時腎上腺無法正常分泌皮質醇（正常應激：皮質醇↑10倍）→應激劑量補充Hydrocortisone；輕微壓力（局部麻醉/小手術）：正常口服劑量即可；中度壓力（全身麻醉/中大型手術）：Hydrocortisone 50-75mg IV×24-48hr；重大手術：100-150mg IV×48-72hr→逐步減量','所有患者均需應激劑量','長期類固醇患者無需應激劑量'],1,
'HPA軸抑制判斷（困難）：（1）Prednisone>20mg/day×>3週→幾乎確定抑制；（2）<5mg/day→不確定抑制（若有症狀→ACTH stimulation test）；（3）5-20mg/day×3-12月→不確定→ACTH stimulation test最準確。Cortrosyn test（ACTH刺激試驗）：250μg IV→60min後Cortisol>18-20μg/dL→正常反應（HPA完整）。'),
]},
{id:'c',t:'免疫抑制/調節藥',em:'🛡️',qs:[
Q('移植免疫抑制「三聯療法」的組成？',
['只需一種藥物','標準三聯：（1）CNI（Calcineurin inhibitor）：Tacrolimus（首選）或Cyclosporine→IL-2↓→T細胞增殖↓；（2）抗代謝藥：Mycophenolate mofetil（MMF，IMPDH抑制→嘌呤合成↓）或Azathioprine；（3）類固醇（Prednisolone，廣效免疫抑制）；急性排斥：高劑量甲基潑尼松龍（Methylprednisolone pulse）；難治性排斥：Antithymocyte Globulin（ATG）','只需類固醇','Cyclosporine+Azathioprine（舊方案）'],1,
'移植排斥類型：（1）超急性（分鐘-小時）：預先存在的抗體（ABO不合）→體液性→預防（crossmatch）；（2）急性（數天-數月）：T細胞媒介（細胞性）最常見→類固醇/ATG治療；（3）慢性（年）：抗體媒介（Donor-specific antibody, DSA）→纖維化→難治療。CNI腎毒性：長期→慢性移植腎病變→腎功能下降（非排斥，而是藥物毒性）→監測Tacrolimus谷值。'),
Q('TNF-α拮抗劑（如Adalimumab）使用前的強制篩查？',
['無需篩查，立即使用','（1）潛伏TB（LTBI）篩查：TST或IGRA→陽性→胸部X光排除活動性TB→INH預防治療9月（至少1月）→再開始生物製劑；（2）HBV篩查：HBsAg/HBcAb→陽性→Entecavir/TDF預防性治療（防再活化）；（3）活動性感染→禁止；（4）心衰竭（EF<50%）→禁忌或謹慎；（5）基礎感染狀態評估（HIV等）','只篩查HBV','只篩查結核'],1,
'TNF-α在免疫監控的重要性：（1）維持肉芽腫完整性（對抗TB、組織胞漿菌等）；（2）TNF-α抑制→肉芽腫破壞→潛伏感染再活化。機會感染譜：TB（最重要）+細胞內菌（組織胞漿菌、球孢子菌、利什曼原蟲）+病毒（HBV再活化）。監測中：每3-6月→感染症狀詢問，必要時TST/IGRA重複。'),
Q('Rituximab（Anti-CD20）引起PML（進展性多焦點白質腦病）的機制？',
['Rituximab直接神經毒性','PML機制：JC病毒（多瘤病毒）→在大多數人潛伏（腎臟/腦）→Rituximab→B細胞↓（B細胞是JC病毒潛伏庫+控制JC病毒的免疫監控↓）→JC病毒再活化→少突膠質細胞（Oligodendrocyte）感染→脫髓鞘→PML（嚴重認知/神經功能喪失）；發生率：<1%（NHL治療），預後差（死亡率30-50%）；治療：停藥+支持（無特效抗JC病毒藥，Mirtazapine/5-HT拮抗可能有幫助但無確切療效）','Rituximab直接攻擊神經','只在HIV患者發生'],1,
'PML高危：（1）Natalizumab（抗VLA-4, MS治療）：JC病毒抗體陽性+高劑量+長療程→PML風險最高（1-4%）；（2）Rituximab/CD20拮抗劑：NHL/自體免疫疾病；（3）嚴重HIV（CD4<100）；（4）其他嚴重免疫抑制。JC病毒抗體（JCV-Ab）：監測工具（Natalizumab尤重要）→陽性+高index→PML風險↑→考慮換藥。'),
Q('Tacrolimus vs Cyclosporine的差異？',
['兩者完全相同','Tacrolimus：結合FKBP12→抑制Calcineurin→更強效（比Cyclosporine強10-100倍）；副作用：神經毒性（震顫/頭痛, 更多）、新發DM（β細胞毒性, 更多）；Cyclosporine：結合Cyclophilin→抑制Calcineurin；副作用：牙齦增生、多毛症（更多）、高血壓（兩者均有）；目前移植首選：Tacrolimus（更強效+更少牙齦/多毛副作用）','Cyclosporine更強效','Tacrolimus無腎毒性'],0,
'CNI腎毒性機制（兩者相同）：入球小動脈收縮→腎小球灌注↓→急性腎毒性（可逆）；長期→腎小管間質纖維化→慢性腎病（不可逆）→監測Tacrolimus谷值（目標：腎移植術後早期8-12 ng/mL, 穩定期5-8 ng/mL）。mTOR抑制劑（Sirolimus/Everolimus）：不收縮腎血管→無直接腎毒性，但影響傷口癒合（不用於移植術後早期）。'),
Q('生物製劑（Biologic agents）的種類及作用靶點？',
['只有TNF-α拮抗劑一類','（1）TNF-α拮抗：Infliximab（嵌合型）/Adalimumab（全人源型）/Etanercept（Fc融合蛋白）→RA/IBD/銀屑病；（2）IL-1拮抗：Anakinra/Rilonacept/Canakinumab→自發性發炎/急性痛風；（3）IL-6拮抗：Tocilizumab（IL-6R拮抗）→RA/CRS（Cytokine Release Syndrome）；（4）IL-17拮抗：Secukinumab→銀屑病/PsA；（5）IL-23拮抗：Guselkumab→銀屑病；（6）T細胞共刺激阻斷：Abatacept（CTLA-Ig）→RA；（7）B細胞：Rituximab（CD20）/Belimumab（BLyS/BAFF拮抗，SLE）','只有IL-6靶點','生物製劑只用於腫瘤'],1,
'生物製劑感染風險階梯（由高至低）：Rituximab（深度B細胞清除）>TNF-α拮抗劑（TB高危）>IL-6拮抗劑>IL-17拮抗劑（黏膜念珠菌↑）>IL-23拮抗劑>T細胞共刺激（Abatacept，相對安全）。CRS（Cytokine Release Syndrome）：CAR-T細胞治療的主要毒性→Tocilizumab（IL-6R拮抗）是標準治療（Dexamethasone輔助）。'),
]},
boss:[
Q('30歲Graves病女性（妊娠8週），FT4極高。治療方案？',
['立即放射碘（¹³¹I）','第一孕期→PTU（不用MMI, 因MMI可能致畸）；劑量：PTU 100-150mg TID→每4週監測FT4→目標FT4在正常上限（甲亢輕度比甲低更安全）；β阻斷劑：Propranolol可短期使用→控制心悸/震顫（不長期用，可能影響胎兒心率）；¹³¹I：妊娠絕對禁忌（胎兒甲狀腺在12週後開始發育→放射碘→胎兒甲狀腺破壞→先天性甲低）；第二孕期換回MMI（PTU肝毒性）','只用Methimazole','立即手術切除'],1,
'Graves病妊娠特點：（1）妊娠早期→甲亢惡化（hCG交叉刺激TSH受器）；（2）妊娠中期→自然改善（免疫耐受）；（3）分娩後→甲亢急性惡化（免疫反彈）。胎兒監測：TSI/TRAb（Graves病活動性抗體）→若高→可穿越胎盤→新生兒一過性甲亢（需監測新生兒FT4）。母親高FT4→胎兒甲狀腺抑制→PTU也可穿越胎盤→胎兒甲低風險（控制在最低有效劑量）。'),
Q('65歲RA患者，Methotrexate+Adalimumab治療中，出現急性高燒+呼吸困難（PaO₂/FiO₂=250）。鑑別診斷？',
['RA急性惡化','鑑別：（1）Methotrexate肺炎（MTX pneumonitis）：發燒/乾咳/呼吸困難/間質浸潤，嗜酸球↑（30%），排除感染後診斷→停MTX+類固醇；（2）TNF-α拮抗劑相關感染：機會性感染（TB/NTM/PCP/組織胞漿菌）→支氣管鏡+培養→抗感染；（3）PCP（Pneumocystis Pneumonia）：LDH↑, β-D-glucan↑, CT毛玻璃影→TMP-SMX治療；必須積極鑑別（感染→類固醇→惡化；MTX肺炎→感染治療無效）','只需繼續原治療','立即加大Adalimumab劑量'],0,
'MTX肺炎（MTX Pneumonitis）：RA患者MTX治療1-2%發生率→發燒+乾咳+呼吸困難+間質浸潤→需排除感染（尤其PCP）→支氣管肺泡灌洗（BAL）+培養。停MTX+Prednisolone（0.5-1mg/kg/day）→多數可恢復。PCP預防：RA/SLE/ANCA血管炎+免疫抑制→TMP-SMX DS 3次/週（或Dapsone/Atovaquone過敏時）。'),
Q('50歲SLE患者，腎炎Class III（增殖型），開始MMF+Prednisolone誘導治療。6個月後尿蛋白無改善。下一步？',
['換用Chloroquine','（1）確認服藥依從性（MMF血中濃度）；（2）非反應→考慮換用Cyclophosphamide IV pulse（Eurolupus方案或NIH方案）+/-加用Rituximab（Anti-CD20）；（3）Hydroxychloroquine：加入所有SLE患者（若無禁忌）→減少復發+器官損傷；（4）Voclosporin（新型CNI）+MMF組合→LN新選擇（AURORA試驗）；（5）Belimumab（Anti-BLyS/BAFF）：SLE生物製劑→可加入','增加MMF劑量','停所有免疫抑制'],1,
'難治型Lupus Nephritis（LN）：（1）Class III/IV誘導失敗→Cyclophosphamide IV（Eurolupus: 500mg q2週×6次，毒性較NIH低）；（2）Rituximab Off-label：難治型LN（LUNAR試驗陰性，但臨床實踐仍用）；（3）新藥：Voclosporin（CNI, AURORA試驗, 完整緩解率↑）+Anifrolumab（抗I型IFN受器, TULIP試驗, SLE活動度↓）。LN監測：尿蛋白/肌酐比值（UPCR）, eGFR, C3/C4, anti-dsDNA。'),
Q('一位使用Infliximab治療IBD的患者出現Infliximab不反應。原因及處置？',
['只能換其他藥物類別','原發性不反應（Primary non-response）：天生無法反應（可能不同免疫路徑，非TNF-α主導）→換生物製劑類別（IL-12/23拮抗劑Ustekinumab or anti-integrin Vedolizumab）；繼發性不反應（Secondary non-response）：（1）藥物濃度↓：劑量不足/抗藥體（Anti-drug antibody, ADA）→TDM（測Infliximab谷值+ADA）→谷值低但ADA低→劑量↑；谷值低+ADA高→換其他TNF-α拮抗劑（Adalimumab）；（2）感染（排除）','立即停Infliximab','只需增加劑量'],1,
'IBD TDM（Therapeutic Drug Monitoring）：Infliximab谷值>3μg/mL（Crohn\'s）or>5（UC）→治療反應最佳。ADA（anti-drug antibody）→加速清除+藥效↓→若ADA(+)且低谷值→換不同TNF-α拮抗劑（不交叉）或加免疫調節劑（Azathioprine/MMF）→抑制ADA形成（聯合治療↓ADA率）。Vedolizumab（anti-α4β7整合素）：腸道選擇性（不影響全身免疫）→感染機會較TNF-α拮抗劑少。'),
Q('20歲系統性紅斑狼瘡（SLE）患者，長期Hydroxychloroquine（HCQ）使用的視網膜毒性監測？',
['不需要眼科監測','HCQ視網膜病變（Hydroxychloroquine retinopathy）：牛眼病變（Bull\'s eye maculopathy）→感光細胞受損→視野缺損→不可逆；累積劑量>1000g or 使用>5年高危；監測：AAO建議→基礎眼科評估→每年（使用>5年後）或更早（高危族群：腎衰竭/肝衰竭/高劑量）；篩查：SD-OCT（最敏感）+VF10-2（自動視野）→早期發現→停藥（仍可能進展）；最安全劑量：<5mg/kg/day（依真實體重）','視網膜毒性只在高劑量時','HCQ無視網膜毒性'],1,
'HCQ的重要性（SLE）：減少復發（36-50%）+降低腎炎進展+心血管保護+抗血栓+降低死亡率→所有SLE患者均應使用（除非禁忌）。視網膜病變危險因素：（1）累積劑量>1000g（最重要）；（2）高劑量（>5mg/kg/day）；（3）使用>5-7年；（4）腎/肝功能不全；（5）黃斑部病變既往史。早期停藥→可阻止進展；但已有視野缺損→部分持續進展（HCQ在視網膜中儲存多年）。'),
]},

/* ===== M10 綜合特殊用藥 ===== */
{id:10,title:'綜合特殊用藥',em:'⭐',c:'#845EF7',
u:[
{id:'a',t:'抗凝血與血栓藥',em:'🩸',qs:[
Q('Warfarin的機制及INR監測目標？',
['阻斷凝血酶直接','抑制維生素K環氧化物還原酶（VKOR）→維生素K活化（還原型）↓→凝血因子II/VII/IX/X（依賴VitK的γ-羧化）合成↓+蛋白C/S↓；INR目標：一般適應症（AF/DVT/PE/機械瓣）=2-3；機械二尖瓣/高危血栓=2.5-3.5；監測頻率：穩定→每月；藥物/飲食改變→2-3天後複查','阻斷血小板活化','阻斷纖維蛋白原'],1,
'Warfarin CYP2C9/VKORC1基因多態性：影響劑量個體差異（部分機構使用基因型引導起始劑量）。飲食交互作用：富含維生素K食物（深綠色蔬菜）→INR↓（穩定攝取，不需完全避免）。Warfarin過量（INR>10或出血）：（1）停藥+口服VitK（INR高但無出血）；（2）IV VitK+PCC（4-factor Prothrombin Complex Concentrate）或FFP（緊急逆轉，如顱內出血）。'),
Q('直接口服抗凝劑（DOAC）的優勢及禁忌？',
['需要定期INR監測','優勢：口服固定劑量（無需TDM）、起效快（2-4hr）、較少食物交互作用（vs Warfarin VitK食物）；Dabigatran（凝血酶直接抑制劑）/Rivaroxaban/Apixaban/Edoxaban（Xa因子抑制劑）；禁忌：（1）機械心臟瓣膜（再次嚴重血栓/出血）；（2）重度腎衰竭（Dabigatran禁，eGFR<30；其他DOAC謹慎用）；（3）妊娠（胎盤穿透→胎兒抗凝）；（4）嚴重肝衰竭','所有情況均優於Warfarin','DOAC無需腎功能評估'],0,
'DOAC逆轉劑：（1）Dabigatran→Idarucizumab（Praxbind）：單抗，完全逆轉，FDA核准；（2）Xa因子抑制劑（Rivaroxaban/Apixaban/Edoxaban）→Andexanet alfa（AndexXa）：Xa誘餌，FDA核准；PCC（4-factor）：所有DOAC的非特異性逆轉選項（適用於無特異性逆轉劑時）。DOAC腎功能監測：每年評估eGFR（腎衰竭→DOAC蓄積→出血）。'),
Q('抗血小板藥物（Aspirin+Clopidogrel）的DAPT（雙重抗血小板療法）適應症？',
['只需Aspirin單藥','ACS（急性冠脈症候群）及PCI後：DAPT（Aspirin+P2Y12抑制劑）標準療程；NSTEMI/PCI：至少12個月（高出血風險→6個月）；STEMI/PCI：至少12個月；穩定型冠心病PCI：1-6個月（依支架類型）；Ticagrelor/Prasugrel比Clopidogrel更強效（更少CYP2C19代謝變異）→ACS首選；出血風險高→縮短DAPT+早換為單抗血小板','只需Clopidogrel','DAPT只用於靜脈血栓'],1,
'P2Y12抑制劑比較：Clopidogrel（前藥, CYP2C19代謝）→「慢代謝者」（CYP2C19 PM）→活性代謝物↓→療效↓→CYP基因型可指導用藥；Ticagrelor（直接作用，可逆，更快起效/失效）→ACS首選（PLATO試驗）；Prasugrel（強效前藥，不可逆）→ACS+PCI（TRITON試驗）→禁忌：腦中風史/TIA（出血性中風↑）、年齡>75歲（謹慎）、體重<60kg（謹慎）。'),
Q('Heparin（肝素）引起的HIT（肝素誘發血小板減少症）的診斷及治療？',
['停Heparin即可','HIT診斷（4T評分）：血小板↓>50%+時間（Heparin開始5-10天）+血栓（靜脈/動脈）+其他原因排除；HIT抗體（PF4/Heparin抗體）→免疫媒介血小板活化→矛盾性血栓（Thrombosis）；治療：（1）立即停所有肝素（包括沖管用！）；（2）換用非肝素抗凝劑：Argatroban（直接凝血酶抑制劑, IV, 肝代謝）或Fondaparinux（Xa因子抑制劑, SC）；（3）血小板正常後→換口服抗凝（Warfarin或DOAC）；（4）禁止：輸血小板（→加重血栓）','輸血小板','換Warfarin'],1,
'HIT（Type II）：免疫媒介（PF4/Heparin複合物→IgG→FcγRIIa活化血小板→活化凝血）→矛盾現象：血小板↓但血栓↑（不是出血）。4T評分≥6→高機率HIT→立即停Heparin+換抗凝→確認抗體（ELISA/SRA）。Fondaparinux：合成Xa抑制劑（純Xa靶點, 不與PF4複合）→HIT時使用理論上安全，但非所有地方有IV製劑。'),
Q('靜脈血栓栓塞（VTE）的抗凝治療期程？',
['所有VTE均需長期抗凝','可誘發VTE（手術/制動/妊娠，一過性誘因）：3月；初次DVT/PE（無明確誘因）：3-6月；反覆VTE：長期（indefinite）；抗磷脂抗體症候群（APS）：長期Warfarin（DOAC在APS效果次於Warfarin）；活動性癌症相關VTE：LMWH或DOAC（Rivaroxaban/Apixaban→CLOT/ADAM VTE試驗）→長期（癌症活動期）；停抗凝評估：D-dimer（低→復發風險低）+影像','只需1個月','全部需要長期'],0,
'VTE復發風險因子：（1）高危：APS, 反覆VTE, 嚴重血栓傾向（Factor V Leiden純合子, Protein S/C缺乏, AT缺乏）→長期抗凝；（2）低危：首次VTE+一過性誘因→3月；（3）中危：首次無誘因→6月后評估（D-dimer、HERDOO2評分）。癌症VTE：LMWH（Dalteparin, CLOT試驗）vs DOAC（HOKUSAI/SELECT-D）→出血風險（腸道癌→消化道出血↑）→Apixaban/Rivaroxaban謹慎選用。'),
]},
{id:'b',t:'呼吸/消化道藥物',em:'💨',qs:[
Q('H₂受器拮抗劑（Ranitidine/Famotidine）vs PPI（Omeprazole）的差異？',
['H₂拮抗劑更強效','H₂拮抗劑：可逆性H₂受器阻斷→壁細胞HCl分泌↓（部分）；PPI：不可逆性H⁺/K⁺-ATPase抑制（質子泵）→更完全抑制（無論何種刺激：食物/組織胺/Gastrin均被阻斷）；臨床效果：PPI>H₂拮抗劑（潰瘍癒合、GERD控制、H. pylori根除）；H₂拮抗劑：速效（1-3hr），用於急性症狀緩解；PPI：需數天達最大效果（需要活化的質子泵）','H₂拮抗劑和PPI機制相同','PPI只用於H. pylori'],0,
'PPI長期使用的副作用（>1年）：（1）C. difficile感染↑（胃酸↓→腸道菌群改變）；（2）低鎂血症（Mg²⁺腸道吸收↓）→抽搐/心律不整（低鎂→低鉀）；（3）骨質疏鬆/骨折↑（Ca²⁺吸收↓, 酸依賴）；（4）維生素B12吸收↓（胃酸需要釋放B12）；（5）腎炎（罕見AIN）。PPI有效性：「按需使用（On-demand）」vs「持續使用」→GERD輕症→按需更合適（減少副作用）。'),
Q('H. pylori根除的三合一療法（Triple therapy）及耐藥問題？',
['只用單一抗菌藥物','標準三合一（14天）：PPI（標準劑量BID）+Clarithromycin 500mg BID+Amoxicillin 1g BID（或Metronidazole）；台灣Clarithromycin耐藥率>20%→成功率↓；替代：（1）含Bismuth四合一（Bismuth+PPI+Metronidazole+Tetracycline, 14天）→對耐藥菌有效；（2）Vonoprazan（Potassium-competitive acid blocker, PCAB）替代PPI→更強酸抑制→更高根除率（PHALCON試驗）；（3）確認根除：治療結束4週後→UBT（尿素呼氣試驗）','只需1週治療','H. pylori不需治療'],0,
'H. pylori根除適應症：消化性潰瘍（必需）、MALT淋巴瘤（可能完全緩解）、早期胃癌根除術後（減少復發）、不明原因缺鐵性貧血、免疫性血小板減少（ITP）部分有效、功能性消化不良（部分）、長期NSAIDs/Aspirin使用者（降低潰瘍風險）。UBT：根除後確認，比血清抗體更準確（血清抗體在根除後仍陽性數年）。'),
Q('支氣管擴張劑在COPD的使用策略（GOLD指引）？',
['只需Salbutamol（SABA）','GOLD A/B（低風險）：LAMA（長效抗膽鹼, Tiotropium）或LABA（長效β₂促效劑, Indacaterol）單藥；GOLD E（高風險/急性惡化）：LAMA+LABA雙支氣管擴張；ICS（吸入類固醇）：只加入血嗜酸球↑（≥300/μL）或急性惡化仍多的患者（不是所有COPD均需ICS, 增加肺炎風險）；急性惡化：SABA（Salbutamol）+SAMA（Ipratropium）+全身類固醇（5-7天）+抗菌（若感染）','只需全身類固醇','LABA+ICS用於所有COPD'],0,
'COPD vs哮喘的支氣管擴張劑選擇差異：哮喘→ICS為基礎（必需）+SABA（PRN）+LABA（中重度附加）；COPD→LAMA/LABA為主（支氣管擴張），ICS「選擇性」加入（血嗜酸球高/頻繁急性惡化）。LAMA（Tiotropium）優於LABA（Salmeterol）在COPD急性惡化預防（UPLIFT試驗）。三聯療法（LAMA+LABA+ICS）：COPD頻繁急性惡化+高嗜酸球者→FULFIL/TRIBUTE試驗支持。'),
Q('Theophylline的機制及TDM的必要性？',
['只是古老藥物，已無用','PDE（Phosphodiesterase）抑制→cAMP↑→支氣管擴張+抗發炎（低劑量）；呼吸肌強化（膈肌）；腺苷受器拮抗（支氣管擴張+CNS刺激）；TI窄（治療/毒性範圍接近）→需TDM：治療濃度10-20μg/mL；毒性（>20）：GI（噁心/嘔吐）、CNS（頭痛/失眠/震顫）、心律不整（VT/心房顫動）；TDM觸發：發燒/藥物改變/吸菸改變（吸菸→CYP1A2誘導→代謝↑）','只用口服','無需監測血中濃度'],1,
'Theophylline現代角色：哮喘/COPD（不是一線，但仍有用於難治型）。CYP1A2底物：吸菸↑CYP1A2→Theophylline代謝↑→血中濃度↓→停菸→代謝↓→濃度↑→毒性。其他CYP1A2抑制劑（Fluvoxamine, Enoxacin）→Theophylline毒性。Aminophylline（IV劑型, Theophylline+Ethylenediamine）：急性重度哮喘的附加治療（雖然SABA+SAMA+全身類固醇可能已足夠）。'),
Q('5-HT₃拮抗劑（Ondansetron）的止嘔機制及適應症？',
['只用於暈動症','阻斷腸道/迷走神經/孤束核（NTS）5-HT₃受器→Vomiting reflex中斷；適應症：（1）化療誘發噁心嘔吐（CINV）—高致嘔性化療（Cisplatin等）首選；（2）術後噁心嘔吐（PONV）；（3）放射治療誘發；副作用：QTc延長（Ondansetron大劑量IV→監測QTc）、頭痛、便秘（5-HT₃阻斷→腸道蠕動↓）；不適合：抗帕金森（多巴胺途徑）或暈動症（前庭受器不同）','阻斷D₂受器','只用於PONV'],1,
'CINV管理分層：（1）高致嘔性（HEC, Cisplatin）：5-HT₃拮抗（Ondansetron）+NK-1拮抗（Aprepitant）+Dexamethasone+Olanzapine（4聯）；（2）中致嘔性（MEC）：5-HT₃拮抗+Dexamethasone±NK-1拮抗；（3）低致嘔性：Dexamethasone單藥。5-HT₃拮抗劑二代：Palonosetron（長效, t₁/₂=40hr）→高/中致嘔首選（比Ondansetron更持久）。'),
]},
{id:'c',t:'抗癌與特殊藥物',em:'🎯',qs:[
Q('烷化劑（Cyclophosphamide）的主要毒性及「Mesna」的保護作用？',
['只有骨髓抑制','Cyclophosphamide代謝→Acrolein（丙烯醛，膀胱毒素）→出血性膀胱炎（haemorrhagic cystitis）；Mesna（2-sulfanylethane-1-sulfonic acid）：巰基（-SH）與Acrolein結合→無毒複合物→尿液排除→保護膀胱；高劑量Cyclophosphamide（>1g/m²）→必須給Mesna；其他毒性：骨髓抑制（劑量限制）、不育（生殖腺毒性）、致癌（繼發性白血病/膀胱癌）','骨髓抑制無法預防','Mesna是Cyclophosphamide的解毒劑（針對骨髓毒性）'],0,
'烷化劑毒性記憶（Cyclophosphamide）：（1）出血性膀胱炎（Acrolein）→Mesna+大量水化；（2）骨髓抑制→G-CSF（Filgrastim）；（3）SIADH（大劑量）→低鈉血症；（4）心毒性（高劑量HSCT前調節）；（5）不育→精子/卵子冷凍保存（生育保護）；（6）繼發性惡性腫瘤（EBM-ALL）。Ifosfamide也是烷化劑→更嚴重血尿性膀胱炎+神經毒性（Encephalopathy, 沒有Mesna不可用）→更需大量Mesna。'),
Q('Methotrexate（MTX）的作用機制及亞葉酸（Leucovorin）的解救？',
['只用於感染治療','MTX：二氫葉酸還原酶（DHFR）抑制→四氫葉酸（THF）合成↓→DNA合成（dTMP）↓→細胞增殖↓；高劑量MTX（癌症）→腎毒性+骨髓抑制→Leucovorin（亞葉酸鈣）解救：Leucovorin是THF的前驅物→繞過DHFR→補充THF→恢復正常DNA合成（保護正常細胞）；低劑量MTX（RA/乾癬, 7.5-25mg/週）：葉酸補充（1mg/day）→減少副作用（口腔潰瘍/肝毒性）但不影響療效','阻斷蛋白質合成','MTX無需解救'],0,
'MTX毒性與Leucovorin解救計畫（高劑量）：MTX靜脈輸注→4-6hr後開始Leucovorin（每6-12hr, 持續72hr以上）→同時大量水化+鹼化尿液（提高MTX腎臟溶解度和排除）→定時MTX血中濃度監測（48/72hr）→>0.1μmol/L→繼續Leucovorin直到安全。Glucarpidase（Carboxypeptidase G2）：MTX結構分解酶→高劑量MTX腎功能衰竭時使用。'),
Q('靶向治療（Targeted therapy）：Imatinib（Gleevec）的革命性意義？',
['與傳統化療效果相同','Imatinib：BCR-ABL酪氨酸激酶抑制劑→慢性骨髓白血病（CML）中BCR-ABL融合蛋白（費城染色體t(9;22)）是關鍵致病機制→Imatinib選擇性阻斷BCR-ABL→CML治療革命（1992年診斷到現今CML患者壽命接近正常）；也用：c-Kit突變（GIST, 胃腸道間質瘤）、PDGFR突變；副作用：水腫（PDGFR相關）、肌肉痙攣、GI症狀、肝毒性','只是強力化療藥','Imatinib覆蓋所有癌症'],1,
'精準腫瘤學（Precision oncology）的起點：Imatinib證明靶向特定分子異常（BCR-ABL）可達到「功能性治癒」概念（無治療緩解, TFR）。其他里程碑靶向療法：（1）Trastuzumab（HER2+乳癌）；（2）EGFR抑制劑（Erlotinib, 肺腺癌EGFR突變）；（3）VEGF抑制劑（Bevacizumab, 血管新生）；（4）PD-1/PD-L1抑制劑（Pembrolizumab/Nivolumab, 免疫检查点）。'),
Q('免疫檢查點抑制劑（PD-1/PD-L1拮抗劑）的免疫相關不良反應（irAE）？',
['只有輕微疲倦','解除T細胞抑制→自身免疫活化→irAE（任何器官）：（1）皮膚（最常見）：皮疹/白斑；（2）腸胃：腹瀉/腸炎（嚴重→3-4級→類固醇）；（3）肝臟：肝炎（ALT↑）；（4）內分泌：甲狀腺炎（甲亢→甲低）/垂體炎（最危險,ACTH↓→腎上腺危象）/DM（胰島素依賴型）；（5）肺臟：免疫性肺炎（呼吸困難+X光浸潤）；（6）腎臟：腎炎；嚴重irAE→停藥+高劑量類固醇（Methylprednisolone 1-2mg/kg）','只影響皮膚','irAE是治療無效的表現'],1,
'irAE管理：（1）輕度（1-2級）→繼續ICI+對症治療；（2）中度（2-3級）→暫停ICI+Prednisolone 0.5-1mg/kg；（3）重度（3-4級）→永久停ICI+IV Methylprednisolone+必要時Infliximab（頑固性腸炎）/Mycophenolate（肝炎）；垂體炎：永久性ACTH缺乏（多數不可逆）→長期Hydrocortisone替代。甲狀腺炎：先甲亢（Thyrotoxicosis）→後甲低（Hypothyroidism, 多數永久）→補Levothyroxine。'),
Q('電解質補充藥物：MgSO₄（硫酸鎂）的多種臨床應用？',
['只用於低鎂補充','（1）子癇/子癇前期：IV MgSO₄→預防/控制癲癇（機制：NMDA受器拮抗+Ca²⁺拮抗）；（2）多形性VT（TdP）：Mg²⁺即使正常也有效（穩定動作電位）；（3）支氣管擴張：重度哮喘急性發作（IV MgSO₄→直接支氣管擴張，Ca²⁺阻斷）；（4）早產抑制（Tocolysis）：大劑量MgSO₄→子宮平滑肌↓（但不再首選）；（5）便秘（口服MgO）；毒性：高鎂血症→膝反射消失→呼吸肌麻痺→心搏停止；解毒：Ca gluconate IV（直接拮抗Mg²⁺效應）','只用於嚴重缺鎂患者','MgSO₄只能口服'],1,
'MgSO₄子癇治療：標準方案—負荷4-6g IV over 20min→維持1-2g/hr；監測：膝反射（消失→停藥）、尿量（>25mL/hr）、呼吸（>12次/min）、Mg²⁺濃度（治療範圍4-7 mEq/L）。Ca gluconate（1g IV）備用→高鎂毒性解毒（Ca²⁺快速逆轉Mg²⁺心肺效應）。MgSO₄哮喘：嚴重急性哮喘（SABA+SAMA+全身類固醇後仍不佳）→IV MgSO₄ 2g over 20min→PRAM/BTS評分改善。'),
]},
boss:[
Q('55歲男性，AF+DVT病史，使用Warfarin（INR 2.2）。確診為轉移性大腸癌，開始Oxaliplatin+Capecitabine（XELOX）化療。抗凝如何調整？',
['繼續Warfarin，無需調整','癌症相關VTE（CAT）抗凝首選：LMWH（Dalteparin/Enoxaparin）或DOAC（Rivaroxaban/Apixaban, ADAM VTE/HOKUSAI Cancer VTE試驗）→優於Warfarin（癌症患者Warfarin穩定性差：飲食改變/嘔吐/藥物交互作用/肝轉移→INR波動）；大腸癌+DOAC出血考量：Rivaroxaban/Apixaban→腸道消化道出血↑（結直腸癌高危）→LMWH可能更安全；Capecitabine→CYP2C9抑制→Warfarin代謝↓→INR↑→進一步不穩定','只需停Warfarin，不需抗凝','換Heparin靜脈（最安全）'],1,
'癌症相關VTE（CAT）特點：（1）比非癌症VTE復發率更高（5倍）；（2）出血風險更高（腫瘤侵犯/血小板異常）；（3）Warfarin管理困難（化療→嘔吐→吸收↓/食慾差→VitK攝取↓→INR波動）。腸癌+抗凝：消化道出血高危→LMWH（皮下注射）在許多指引優先（出血可快速逆轉用Protamine）；DOAC若用需監測消化道出血（Apixaban>Rivaroxaban安全性好一些in腸癌）。'),
Q('30歲女性，妊娠12週，DVT確診。抗凝選擇？',
['Warfarin（安全的）','妊娠DVT唯一安全抗凝：LMWH（Enoxaparin）→全妊娠期使用；Warfarin：（1）第6-12週→鼻骨發育不良/Stippled epiphyses（Warfarin embryopathy）；（2）任何孕期大量出血→胎兒顱內出血→禁用；（3）例外：機械心臟瓣膜（高血栓風險）→妊娠中期可考慮Warfarin（INR目標2.5-3.5），分娩前換LMWH；DOAC：動物實驗致畸→妊娠禁忌；分娩後→可換DOAC或Warfarin（哺乳期：兩者均相對安全, Warfarin不進入乳汁/DOAC少量）','DOAC（最方便）','普通Heparin靜脈（需住院）'],0,
'妊娠VTE管理：LMWH（體重調整劑量）全程→分娩前12hr停LMWH（計畫分娩）or 分娩後重新開始。劑量調整：妊娠期Vd↑+腎清除↑→LMWH劑量需增加（每12hr vs 非妊娠每24hr）→Anti-Xa監測（峰值0.6-1.0 IU/mL, 4hr後）。產後：LMWH→至少6週（VTE高危6個月）→可換DOAC/Warfarin（哺乳期：Warfarin和Enoxaparin乳汁中量極少，相對安全）。'),
Q('65歲男性，接受Cisplatin化療後出現急性腎損傷（AKI, Cr↑3倍）。Cisplatin腎毒性的機制及預防？',
['無法預防Cisplatin腎毒性','機制：Cisplatin在腎小管蓄積（近端小管主動轉運攝取）→DNA加合物+氧化損傷→腎小管細胞凋亡→Cr↑；預防：（1）大量水化（NS 1-2L化療前/後）→稀釋腎小管Cisplatin+增加尿量→↓接觸時間；（2）Amifostine（自由基清除劑, 輔助保護, 爭議性）；（3）Mannitol（強迫利尿, 某些方案）；（4）避免合用NSAID/Aminoglycoside（協同腎毒性）；（5）監測腎功能+電解質（低鎂最常見）','直接使用透析預防','只需補鎂'],1,
'Cisplatin腎毒性特點：（1）劑量累積性（每次化療後腎功能稍差）；（2）Cr在治療後3-5天才開始升高（延遲）；（3）低鎂（Cisplatin→腎小管Mg²⁺浪費）：治療中常見→補Mg²⁺（IV MgSO₄）；（4）腎功能嚴重→Cisplatin禁用→換Carboplatin（腎毒性小但骨髓毒性大）。水化協議（hydration protocol）：NS 1L/hr×4-6hr→Cisplatin輸注→NS 1L/hr×4-6hr→維持尿量>100mL/hr→Mannitol±KCl±MgSO₄補充。'),
Q('45歲女性，乳癌（HER2+）使用Trastuzumab（Herceptin）治療。需要監測哪種心臟毒性？',
['Trastuzumab無心臟毒性','Trastuzumab：HER2拮抗（ErbB2）→心肌也表達HER2（心肌修復所需）→阻斷HER2→心肌功能障礙→左心室功能不全（LVEF↓）+心衰竭；特點：通常可逆（停藥後改善, 不像Anthracycline的不可逆損傷）；監測：治療前基礎LVEF（超音波心動圖或MUGA scan）→每3個月監測（治療期間）→LVEF↓10%且<50%→暫停→LVEF恢復後重啟；禁忌：LVEF<50%基礎值','只監測骨髓抑制','只監測腎功能'],1,
'Anthracycline vs Trastuzumab心臟毒性：Anthracycline（如Doxorubicin）→不可逆心肌細胞死亡（Type I）→劑量累積性→避免超過550mg/m²終身劑量；Trastuzumab→可逆心肌功能障礙（Type II）→停藥後常恢復。兩者合用→協同心毒性↑→需更嚴格監測。Cardio-oncology：新興次專科→腫瘤患者心血管管理。'),
Q('70歲男性，口服抗凝劑（Rivaroxaban）出現頭痛+嘔吐+右側偏癱。CT確認顱內出血（ICH）。緊急逆轉抗凝策略？',
['只需保守治療，等待DOAC代謝','顱內出血+DOAC（Rivaroxaban, Xa因子抑制劑）→緊急逆轉：Andexanet alfa（AndexXa）：FDA核准特異性逆轉Xa抑制劑（Rivaroxaban/Apixaban）→直接中和血中遊離Xa抑制劑→快速恢復凝血（ANNEXA-4試驗）；替代（無Andexanet時）：4-factor PCC（Profilnine/Kcentra）→補充凝血因子→非特異性逆轉；同時：神經外科評估（是否需手術）+嚴格血壓控制（SBP<140mmHg）+頭部抬高30度','等待自然逆轉（DOAC t₁/₂短）','給Vitamin K（對DOAC無效）'],1,
'DOAC逆轉劑選擇：（1）Dabigatran（凝血酶直接抑制劑）→Idarucizumab（Praxbind, 3×Dabigatran親和力, 完全逆轉）；（2）Rivaroxaban/Apixaban/Edoxaban（Xa因子抑制劑）→Andexanet alfa（但費用極高）或4-factor PCC（替代, 快速可及）；（3）緊急手術/生命威脅出血→不論哪種DOAC→4-factor PCC（最快速廣泛可及）。Vitamin K對DOAC完全無效（DOAC不影響VitK依賴性凝血因子的活化，直接抑制活化的因子）。'),
]},
];/* ===== END MILESTONES ===== */

window.ML_P = { id:'p', ms };
console.log('[MedLingo] 藥理學題庫載入成功！里程碑數：' + ms.length);
})();
